# This file was generated by the {rix} R package v0.15.0 on 2025-07-10
# with following call:
# >rix(date = "2025-07-07",
#  > r_pkgs = c("languageserver",
#  > "dplyr",
#  > "Seurat"),
#  > system_pkgs = NULL,
#  > git_pkgs = list(package_name = "httpgd",
#  > repo_url = "https://github.com/nx10/httpgd",
#  > commit = "dd6ed3a687a2d7327bb28ca46725a0a203eb2a19"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-07-07.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      dplyr
      languageserver
      Seurat;
  };
 
    httpgd = (pkgs.rPackages.buildRPackage {
      name = "httpgd";
      src = pkgs.fetchgit {
        url = "https://github.com/nx10/httpgd";
        rev = "dd6ed3a687a2d7327bb28ca46725a0a203eb2a19";
        sha256 = "sha256-vs6MTdVJXhTdzPXKqQR+qu1KbhF+vfyzZXIrFsuKMtU=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          unigd
          cpp11
          AsioHeaders;
      };
    });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ httpgd rpkgs  system_packages   ];
  
}
