# This file was generated by the {rix} R package v0.15.0 on 2025-07-12
# with following call:
# >rix(date = "2025-07-07",
#  > r_pkgs = c("languageserver",
#  > "tidyverse",
#  > "Seurat",
#  > "readxl",
#  > "writexl",
#  > "qs2",
#  > "targets",
#  > "tarchetypes",
#  > "hdf5r",
#  > "scDblFinder"),
#  > system_pkgs = NULL,
#  > git_pkgs = list(list(package_name = "httpgd",
#  > repo_url = "https://github.com/nx10/httpgd",
#  > commit = "dd6ed3a687a2d7327bb28ca46725a0a203eb2a19"),
#  > list(package_name = "scMisc",
#  > repo_url = "https://github.com/mihem/scMisc",
#  > commit = "e2ebddcb779b935551f14216514c0429616fc91d"),
#  > list(package_name = "presto",
#  > repo_url = "https://github.com/immunogenomics/presto",
#  >      commit = "7636b3d0465c468c35853f82f1717d3a64b3c8f6")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-07-07.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      hdf5r
      languageserver
      qs2
      readxl
      scDblFinder
      Seurat
      tarchetypes
      targets
      tidyverse
      writexl;
  };
 
    httpgd = (pkgs.rPackages.buildRPackage {
      name = "httpgd";
      src = pkgs.fetchgit {
        url = "https://github.com/nx10/httpgd";
        rev = "dd6ed3a687a2d7327bb28ca46725a0a203eb2a19";
        sha256 = "sha256-vs6MTdVJXhTdzPXKqQR+qu1KbhF+vfyzZXIrFsuKMtU=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          unigd
          cpp11
          AsioHeaders;
      };
    });


    presto = (pkgs.rPackages.buildRPackage {
      name = "presto";
      src = pkgs.fetchgit {
        url = "https://github.com/immunogenomics/presto";
        rev = "7636b3d0465c468c35853f82f1717d3a64b3c8f6";
        sha256 = "sha256-Sfjx5e0drUrRA9f0gxmeN8Z3cdz6Q3LBVWM3tV6k8R0=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          Rcpp
          data_table
          dplyr
          tidyr
          purrr
          tibble
          Matrix
          rlang
          RcppArmadillo;
      };
    });


    enrichR = (pkgs.rPackages.buildRPackage {
      name = "enrichR";
      src = pkgs.fetchgit {
        url = "https://github.com/wjawaid/enrichR";
        rev = "c303bd30f58a04e01f29576364462e9fb6130ea2";
        sha256 = "sha256-HoL6V9GsK1ZthwWH2Gs7JAFlgOJA5mvqN/ecycBUDwI=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          httr
          curl
          rjson
          ggplot2
          WriteXLS;
      };
    });

    scMisc = (pkgs.rPackages.buildRPackage {
      name = "scMisc";
      src = pkgs.fetchgit {
        url = "https://github.com/mihem/scMisc";
        rev = "e2ebddcb779b935551f14216514c0429616fc91d";
        sha256 = "sha256-Atmr+vGfJxNc5HK+UgpnSIeZ1fYKWEzD3Dt2va1xoFE=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          Seurat
          readr
          glue
          viridis
          ggplot2
          pheatmap
          homologene
          dplyr
          tibble
          magrittr
          clustifyr
          ggrepel
          writexl
          ggsignif
          patchwork
          rstatix
          readxl
          tidyr
          speckle
          limma
          RColorBrewer
          factoextra
          FactoMineR
          Matrix
          ggpubr
          tidyselect
          stringr
          forcats;
      } ++ [ enrichR ];
    });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ httpgd scMisc presto rpkgs  system_packages   ];
  
}
